### PR TITLE
Relocate command full path update

### PR DESCRIPTION
**Pull request by ZFW777**
updated relocate command to support full path relocating.

### CODE REVIEW

**Comment by ZFW777** [comment]
fix #186

**Comment by yamgent** [comment]
Need to accept spaces in path (e.g. Usernames might have spaces)

**Comment by yamgent** [comment]
Thanks for the space fix. New bug: after I do a relocate, all changes will not be saved (it only reflects on the GUI).

**Comment by ZFW777** [comment]
Should work fine now

**Review by yamgent — APPROVED** [review]

**Pull request merged**
